const TERMS = [
  // Philosophical & Decision-Making Principles
  "Occam's Razor",
  "Hanlon's Razor",
  "Hitchens's Razor",
  "Hume's Guillotine",
  "Popper's Falsifiability Principle",
  "Brandolini's Law",
  "Sturgeon's Law",
  "Hofstadter's Law",
  "Parkinson's Law",
  "The Peter Principle",
  "Dilbert Principle",
  "Sayre's Law",
  "Iron Law of Oligarchy",
  "Littlewood's Law",
  "Benford's Law of Controversy",
  "Dunning-Kruger Effect",
  "Gentry's Law",
  "Chesterton's Fence",
  "Second-Order Thinking",
  "Inversion Principle",
  "Map-Territory Relation",
  "Causal Overdetermination",
  "Nirvana Fallacy",
  "Survivorship Bias",
  "Sunk Cost Fallacy",
  "Regression to the Mean",
  "Lindy Effect",

  // Technology, Computing & Systems
  "Moore's Law",
  "Wirth's Law",
  "Amdahl's Law",
  "Gustafson's Law",
  "Brooks's Law",
  "Conway's Law",
  "Linus's Law",
  "Metcalfe's Law",
  "Reed's Law",
  "Gilder's Law",
  "Beckstrom's Law",
  "Kryder's Law",
  "Cooper's Law",
  "Joy's Law",
  "Zawinski's Law",
  "Tesler's Law",
  "Bushnell's Law",
  "Fitts's Law",
  "Hick's Law",
  "Jakob's Law",
  "Miller's Law",
  "Postel's Law",
  "Gall's Law",
  "Lehman's Laws of Software Evolution",
  "Amara's Law",
  "Knuth's Optimization Principle",
  "Worse Is Better",
  "Law of Demeter",
  "CAP Theorem",
  "End-to-End Principle",
  "Fallacies of Distributed Computing",
  "Technical Debt",
  "Cargo Cult Programming",
  "Bike-Shedding Effect",
  "Premature Optimization",
  "Shirky Principle",

  // Economics, Management & Human Behaviour
  "Goodhart's Law",
  "Campbell's Law",
  "Lucas Critique",
  "Cobra Effect",
  "Pareto Principle",
  "Price's Law",
  "Zipf's Law",
  "Gresham's Law",
  "Thiers's Law",
  "Jevons Paradox",
  "Say's Law",
  "Engel's Law",
  "Okun's Law",
  "Hotelling's Law",
  "Wagner's Law",
  "Gibson Paradox",
  "Good Samaritan Law",
  "Iron Law of Wages",
  "Invisible Hand",
  "Information Asymmetry",
  "Paradox of Choice",
  "Overton Window",
  "Matthew Effect",
  "Tragedy of the Commons",
  "Principal-Agent Problem",
  "Moral Hazard",
  "Adverse Selection",
  "Nash Equilibrium",
  "Ratchet Effect",
  "Path Dependence",
  "Switching Costs",
  "Lock-In Effect",
  "Winner-Take-All Dynamics",
  "Long Tail",
  "Power Law",
  "Abilene Paradox",
  "Lindblom's Incrementalism",

  // Internet Culture & Communication
  "Godwin's Law",
  "Poe's Law",
  "Cunningham's Law",
  "Streisand Effect",
  "Betteridge's Law of Headlines",
  "Skittles' Law",
  "Danth's Law",
  "Pommer's Law",
  "DeMyer's Laws",
  "Cohen's Law",
  "Scannell's Law",
  "Shaker's Law",

  // Psychology & Cognitive Science
  "Baader-Meinhof Phenomenon",
  "Barnum Effect",
  "Halo Effect",
  "Hawthorne Effect",
  "Semmelweis Reflex",
  "Gell-Mann Amnesia Effect",
  "Frequency Illusion",
  "Confirmation Bias",
  "Availability Heuristic",
  "Anchoring Effect",
  "Framing Effect",
  "Fundamental Attribution Error",
  "Spotlight Effect",
  "Planning Fallacy",
  "Optimism Bias",
  "Negativity Bias",
  "Status Quo Bias",
  "Loss Aversion",
  "Endowment Effect",
  "IKEA Effect",
  "Yerkes-Dodson Law",
  "Weber-Fechner Law",
  "Dunbar's Number",

  // Science, Systems & Complexity
  "Butterfly Effect",
  "Observer Effect",
  "Red Queen Hypothesis",
  "Emergence",
  "Antifragility",
  "Black Swan",
  "Chaos Theory",
  "Feedback Loop",
  "Tipping Point",
  "Critical Mass",
  "Network Effect",
  "Stigler's Law of Eponymy",
  "Clarke's First Law",
  "Finagle's Law",
  "Murphy's Law",
  "Muphry's Law",
  "Kidlin's Law",
  "Kerckhoffs's Principle",
  "Benford's Law",

  // Social & Political Dynamics
  "Iron Triangle",
  "Revolution of Rising Expectations",
  "Overton Window Drift",
  "Collective Action Problem",
  "Free Rider Problem",
  "Tragedy of the Anticommons",
  "Coordination Problem",
  "Social Loafing",
  "Diffusion of Responsibility",
  "Pluralistic Ignorance",
  "Spiral of Silence",
  "Backfire Effect",
  "Semiotic Democracy",
  "Manufactured Consent",
  "Preference Falsification",

  // Design, Media & Communication Theory
  "McLuhan's Tetrad",
  "Medium Is the Message",
  "Signal-to-Noise Ratio",
  "Attention Economy",
  "Filter Bubble",
  "Echo Chamber",
  "Illusion of Transparency",
  "Curse of Knowledge",
  "Curse of Dimensionality",
  "Uncanny Valley",
  "Peak-End Rule",
  "Zeigarnik Effect",
  "Mere Exposure Effect",
  "Pratfall Effect",

  // Strategy & Decision Theory
  "Minimax Theorem",
  "Pareto Efficiency",
  "Prisoner's Dilemma",
  "Chicken Game",
  "Stag Hunt",
  "Battle of the Sexes",
  "Matching Pennies",
  "War of Attrition",
  "Schelling Point",
  "Focal Point",
  "Mutually Assured Destruction",
  "Brinkmanship",
  "Salami Tactics",
  "Salami Slicing Strategy",
  "Boiling Frog Syndrome",
  "Frog in the Well",
  "Pyrrhic Victory",
  "Hollow Victory",
  "Reversible vs Irreversible Decisions",
  "OODA Loop",
  "Boyd Cycle",
  "Fog of War",
  "Friction in War",
  "Law of Unintended Consequences",
  "Cobra Effect Paradox",
  "Peltzman Effect",
  "Lucas Wedge",
  "Ricardian Equivalence",
  "Laffer Curve",
  "Phillips Curve",
  "Kuznets Curve",
  "Environmental Kuznets Curve",
  "Kondratiev Wave",
  "Creative Destruction",
  "Disruptive Innovation",
  "Innovator's Dilemma",
  "Crossing the Chasm",
  "Technology Adoption Lifecycle",
  "Diffusion of Innovations",
  "Rogers' Diffusion Curve",
  "Hype Cycle",
  "Peak of Inflated Expectations",
  "Trough of Disillusionment",
  "Plateau of Productivity",
];
